# Generated by Django 5.1.6 on 2025-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_contactmessage_promotion_cart_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
