# Generated by Django 5.1.6 on 2025-04-09 13:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_ram_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=core.models.default_list),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.JSONField(blank=True, default=core.models.default_list),
        ),
    ]
