# Generated by Django 5.1.6 on 2025-04-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_address_userprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19)),
                ('expiry', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(default='2 Valdivia Ct, Windsor Mill, MD 21244'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], default='paypal', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carddetails'),
        ),
    ]
