# Generated by Django 5.1.6 on 2025-06-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carddetails_order_billing_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
