# Generated by Django 5.1.6 on 2025-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_contactmessage_delete_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bluetooth Speakers', 'Bluetooth Speakers'), ('Headphones', 'Headphones'), ('Wireless Earbuds', 'Wireless Earbuds'), ('Smartwatches', 'Smartwatches'), ('Screen Protectors', 'Screen Protectors'), ('Phone Cases', 'Phone Cases'), ('Chargers & Cables', 'Chargers & Cables'), ('Power Banks', 'Power Banks'), ('Accessories', 'Accessories'), ('Wearables', 'Wearables'), ('Budget Phones', 'Budget Phones'), ('Flagship Phones', 'Flagship Phones'), ('Gaming Phones', 'Gaming Phones'), ('Tablets', 'Tablets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
