# Generated by Django 5.1.6 on 2025-04-09 13:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=core.models.default_list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.JSONField(blank=True, default=core.models.default_list, null=True),
        ),
    ]
